//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int id { get; set; }
        public string address1 { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string mark { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> uid { get; set; }
    
        public virtual user user { get; set; }
    }
}
