//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int id { get; set; }
        public string detail { get; set; }
        public int uid { get; set; }
        public int shop_id { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    
        public virtual user user { get; set; }
        public virtual shopping shopping { get; set; }
    }
}
