//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> sum_price { get; set; }
        public Nullable<int> shop_id { get; set; }
        public string title { get; set; }
        public Nullable<int> aid { get; set; }
    
        public virtual order order { get; set; }
        public virtual shopping shopping { get; set; }
    }
}
