//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureShopping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_car
    {
        public int id { get; set; }
        public Nullable<int> uid { get; set; }
        public Nullable<int> shopid { get; set; }
        public Nullable<int> shopNum { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<int> aid { get; set; }
        public Nullable<int> productAttributeId { get; set; }
    
        public virtual user user { get; set; }
        public virtual shopping shopping { get; set; }
        public virtual product_attribute product_attribute { get; set; }
    }
}
